/**
 * Pokedex API
 * API to provide access to the pokedex database
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PokemonAbilities } from './pokemonAbilities';

export interface Pokemon { 
    id?: number;
    name?: string;
    lvl?: number;
    evolutionId?: number;
    abilities?: Array<PokemonAbilities>;
    type?: Array<string>;
    image?: string;
}